@server = https://texai-laughing-space-xylophone-5x4ww94j27q9x-8080.preview.app.github.dev

###
GET {{server}}/
###
GET {{server}}/cursos
###
POST {{server}}/cursos
Content-Type: application/json

{"nombre": "Compiladores 2", "creditos": 5}
###
GET {{server}}/cursos/1
###
PATCH {{server}}/cursos/2
Content-Type: application/json

{"nombre": "Lenguajes de Programación"}
###
GET {{server}}/cursos?size=2&page=0
###
GET {{server}}/cursos?size=2&page=0&sort=creditos,desc
###
GET {{server}}/cursos?size=2&page=1&sort=creditos,desc
###
GET {{server}}/cursos/search/findByNombre?nombre=Algoritmos

#############

GET {{server}}/carreras
###
POST {{server}}/carreras
Content-Type: application/json

{"nombre": "Marketing"}
###
GET {{server}}/carreras/2/cursos
###
GET {{server}}/carreras/1/cursos
###
GET {{server}}/cursos/4/carrera?size=2&page=0&sort=creditos,desc